# Generated by Django 6.1.1 on 2026-09-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('users', '0002_client_prestataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_proximite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_disponibilite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_missions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.PositiveIntegerField()),
                ('justification', models.TextField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='demandes.demande')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='users.prestataire')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('demande', 'prestataire')},
            },
        ),
    ]
