# Generated by Django 6.1.1 on 2026-09-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_client_prestataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestataireService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarif_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_proposes', to='users.prestataire')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataires', to='services.service')),
            ],
            options={
                'unique_together': {('prestataire', 'service')},
            },
        ),
    ]
