# Generated by Django 6.1.1 on 2026-09-21 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='missions.mission')),
            ],
        ),
    ]
